              
name: Build Publish

on:
  workflow_call:
    inputs:
      WORKSPACE_REPOSITORY:
        type: string
        required: true
      WORKSPACE_OWNER_REPOSITORY:
        type: string
        required: true
      
      MODULE_FULL_VERSION:
        type: string
        required: true
      MODULE_ONLY_VERSION:
        type: string
        required: true
      MODULE_SUFFIX:
        type: string
        
    secrets:
      USER:
        required: true
      TOKEN:
        required: true

permissions:
  contents: read

jobs:

   buildAndPublish:

    runs-on: ubuntu-latest
    
    env:
      DEPLOY_BRANCH_main: uat prd
      DEPLOY_BRANCH_uat: uat
      DEPLOY_BRANCH_develop: local dev

      MODULE_FULL_VERSION: ${{ inputs.MODULE_FULL_VERSION }}
      MODULE_ONLY_VERSION: ${{ inputs.MODULE_ONLY_VERSION }}
      MODULE_SUFFIX: ${{ inputs.MODULE_SUFFIX }}
      
      WORKSPACE_OWNER_REPOSITORY: ${{ inputs.WORKSPACE_OWNER_REPOSITORY }}
      WORKSPACE_REPOSITORY: ${{ inputs.WORKSPACE_REPOSITORY }}
      
      USER: ${{ secrets.USERNAME }}
      TOKEN: ${{ secrets.TOKEN }}
      
    steps:
    
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'

    - name: Set up Blade
      run: |
        curl -L https://raw.githubusercontent.com/liferay/liferay-blade-cli/master/cli/installers/local | sh
        echo "${HOME}/jpm/bin" >> $GITHUB_PATH
    
    - name: Clone workspace
      uses: actions/checkout@v3
      with:
        repository: ${{ env.WORKSPACE_OWNER_REPOSITORY }}/${{ env.WORKSPACE_REPOSITORY }}
        path: lfrgs-klabindw
        token: ${{ secrets.TOKEN }}
    
    - name: Set up liferay workspace
      run: |
        mkdir -p liferay-workspace
        cp -r lfrgs-klabindw/liferay/* liferay-workspace
        rm -r liferay-workspace/themes/*
        rm -r liferay-workspace/modules/*
        
    - name: Clone Module ${{ github.event.repository.name }}
      uses: actions/checkout@v3
      with:
        path: liferay-workspace/modules/${{ github.event.repository.name }}
        
    - run: ls -lha
      working-directory: liferay-workspace/modules
              
    - name: Build module
      working-directory: liferay-workspace
      run: ./gradlew deploy
    
    - name: Publish module
      working-directory: liferay-workspace
      run: ./gradlew publish
      
    - name: move binaries files to deploy
      run: | 
        for folder in $DEPLOY_BRANCH_${{ github.ref_name }}
        do
          cp -v liferay-workspace/build/docker/deploy/* lfrgs-klabindw/liferay/configs/$folder/deploy
          echo "files moved to /$folder"
        done
    
    - name: push to lfrgs-klabindw
      working-directory: lfrgs-klabindw
      run: |
          git config user.name BotDeploy
          git config user.email BotDeploy@github.com
          git add .
          git commit -m "${{ github.event.repository.name }} $MODULE_FULL_VERSION deploy"
          git push
